### PR TITLE
Do not read useless nodes

### PR DESCRIPTION
**Pull request by Tristramg**
This increases a bit the run time (+20%) but dramatically reduces memory
consumption (divided by 5)

### CODE REVIEW

**Comment by Tristramg** [comment]
@antoine-de please review :)

**Comment by antoine-de** [comment]
seems ok for me :+1: 

What are the impacts on memory usage (and on execution time) ?

**Comment by Tristramg** [comment]
> This increases a bit the run time (+20%) but dramatically reduces memory
consumption (divided by 5)

**Comment by antoine-de** [comment]
plop plop plop, I need to wake up.

nice!

**Pull request merged**
